FROM postgres:18-alpine

ARG POSTGRES_USER=quarkus_user
ARG POSTGRES_DB=recipe_book

ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_DB=$POSTGRES_DB

# Copy initialization scripts
COPY app/db/*.sql /docker-entrypoint-initdb.d/
COPY app/db/schema/*.sql /docker-entrypoint-initdb.d/schema/

# Expose the PostgreSQL port
EXPOSE 5432