-- Insert demo ingredients
INSERT INTO ingredient (description, position, recipe_id)
SELECT ingredients.description,
       ingredients.position,
       r.id
FROM (VALUES ('200g Spaghetti', 1, 'Spaghetti Bolognese'),
             ('300g Ground beef', 2, 'Spaghetti Bolognese'),
             ('400ml Tomato sauce', 3, 'Spaghetti Bolognese'),
             ('500g Chicken thighs', 1, 'Chicken Curry'),
             ('2 tbsp Curry powder', 2, 'Chicken Curry'),
             ('400ml Coconut milk', 3, 'Chicken Curry'),
             ('1 head Romaine lettuce', 1, 'Caesar Salad'),
             ('100g Croutons', 2, 'Caesar Salad'),
             ('50g Parmesan cheese', 3, 'Caesar Salad'),
             ('250g Flour', 1, 'Chocolate Chip Cookies'),
             ('200g Chocolate chips', 2, 'Chocolate Chip Cookies'),
             ('150g Butter', 3, 'Chocolate Chip Cookies'),
             ('200g Arborio rice', 1, 'Mushroom Risotto'),
             ('300g Mixed mushrooms', 2, 'Mushroom Risotto'),
             ('1L Vegetable stock', 3, 'Mushroom Risotto'),
             ('100ml White wine', 4, 'Mushroom Risotto'),
             ('400g White fish fillets', 1, 'Fish Tacos'),
             ('8 pieces Corn tortillas', 2, 'Fish Tacos'),
             ('200g Cabbage', 3, 'Fish Tacos'),
             ('2 pieces Lime', 4, 'Fish Tacos'),
             ('3 large Tomatoes', 1, 'Greek Salad'),
             ('1 large Cucumber', 2, 'Greek Salad'),
             ('200g Feta cheese', 3, 'Greek Salad'),
             ('100g Olives', 4, 'Greek Salad'),
             ('1 medium Red onion', 5, 'Greek Salad'),
             ('400g Beef strips', 1, 'Beef Stir Fry'),
             ('2 pieces Bell peppers', 2, 'Beef Stir Fry'),
             ('3 tbsp Soy sauce', 3, 'Beef Stir Fry'),
             ('3 cloves Garlic', 4, 'Beef Stir Fry'),
             ('3 large Ripe bananas', 1, 'Banana Bread'),
             ('300g All-purpose flour', 2, 'Banana Bread'),
             ('150g Sugar', 3, 'Banana Bread'),
             ('2 pieces Eggs', 4, 'Banana Bread'),
             ('500g Mixed vegetables', 1, 'Vegetable Soup'),
             ('1L Vegetable broth', 2, 'Vegetable Soup'),
             ('1 large Onion', 3, 'Vegetable Soup'),
             ('2 medium Carrots', 4, 'Vegetable Soup')) AS ingredients(description, position, recipe_title)
         JOIN recipe r ON r.title = ingredients.recipe_title;
