-- Insert demo ingredients
INSERT INTO ingredient (name, quantity, position, recipe_id)
SELECT name, quantity, position, r.id
FROM (VALUES ('Spaghetti', '200g', 1, 'Spaghetti Bolognese'),
             ('Ground beef', '300g', 2, 'Spaghetti Bolognese'),
             ('Tomato sauce', '400ml', 3, 'Spaghetti Bolognese'),
             ('Chicken thighs', '500g', 1, 'Chicken Curry'),
             ('Curry powder', '2 tbsp', 2, 'Chicken Curry'),
             ('Coconut milk', '400ml', 3, 'Chicken Curry'),
             ('Romaine lettuce', '1 head', 1, 'Caesar Salad'),
             ('Croutons', '100g', 2, 'Caesar Salad'),
             ('Parmesan cheese', '50g', 3, 'Caesar Salad'),
             ('Flour', '250g', 1, 'Chocolate Chip Cookies'),
             ('Chocolate chips', '200g', 2, 'Chocolate Chip Cookies'),
             ('Butter', '150g', 3, 'Chocolate Chip Cookies'),
             ('Arborio rice', '200g', 1, 'Mushroom Risotto'),
             ('Mixed mushrooms', '300g', 2, 'Mushroom Risotto'),
             ('Vegetable stock', '1L', 3, 'Mushroom Risotto'),
             ('White wine', '100ml', 4, 'Mushroom Risotto'),
             ('White fish fillets', '400g', 1, 'Fish Tacos'),
             ('Corn tortillas', '8 pieces', 2, 'Fish Tacos'),
             ('Cabbage', '200g', 3, 'Fish Tacos'),
             ('Lime', '2 pieces', 4, 'Fish Tacos'),
             ('Tomatoes', '3 large', 1, 'Greek Salad'),
             ('Cucumber', '1 large', 2, 'Greek Salad'),
             ('Feta cheese', '200g', 3, 'Greek Salad'),
             ('Olives', '100g', 4, 'Greek Salad'),
             ('Red onion', '1 medium', 5, 'Greek Salad'),
             ('Beef strips', '400g', 1, 'Beef Stir Fry'),
             ('Bell peppers', '2 pieces', 2, 'Beef Stir Fry'),
             ('Soy sauce', '3 tbsp', 3, 'Beef Stir Fry'),
             ('Garlic', '3 cloves', 4, 'Beef Stir Fry'),
             ('Ripe bananas', '3 large', 1, 'Banana Bread'),
             ('All-purpose flour', '300g', 2, 'Banana Bread'),
             ('Sugar', '150g', 3, 'Banana Bread'),
             ('Eggs', '2 pieces', 4, 'Banana Bread'),
             ('Mixed vegetables', '500g', 1, 'Vegetable Soup'),
             ('Vegetable broth', '1L', 2, 'Vegetable Soup'),
             ('Onion', '1 large', 3, 'Vegetable Soup'),
             ('Carrots', '2 medium', 4, 'Vegetable Soup')) AS ingredients(name, quantity, position, recipe_title)
         JOIN recipe r ON r.title = ingredients.recipe_title
