INSERT INTO preparation_step (description, position, recipe_id)
SELECT steps.description, position, r.id
FROM (VALUES ('Bring a large pot of salted water to boil for the pasta.', 1, 'Spaghetti Bolognese'),
             ('Heat olive oil in a large pan over medium-high heat.', 2, 'Spaghetti Bolognese'),
             ('Add diced onions and cook until translucent, about 5 minutes.', 3, 'Spaghetti Bolognese'),
             ('Add minced garlic and cook for another minute until fragrant.', 4, 'Spaghetti Bolognese'),
             ('Add ground beef and cook, breaking it up with a spoon, until browned all over.', 5,
              'Spaghetti Bolognese'),
             ('Pour in the tomato sauce and add dried herbs (oregano, basil).', 6, 'Spaghetti Bolognese'),
             ('Reduce heat to low and let simmer for 20-25 minutes, stirring occasionally.', 7, 'Spaghetti Bolognese'),
             ('Cook spaghetti according to package directions until al dente.', 8, 'Spaghetti Bolognese'),
             ('Drain pasta and serve topped with the bolognese sauce and parmesan cheese.', 9, 'Spaghetti Bolognese'),
             ('Cut chicken thighs into bite-sized pieces and season with salt and pepper.', 1, 'Chicken Curry'),
             ('Heat vegetable oil in a large skillet over medium-high heat.', 2, 'Chicken Curry'),
             ('Add diced onions and cook until softened and lightly golden, about 6-8 minutes.', 3, 'Chicken Curry'),
             ('Add minced ginger, garlic, and curry powder. Cook until fragrant, about 1 minute.', 4, 'Chicken Curry'),
             ('Add chicken pieces and cook until golden brown on all sides, about 8-10 minutes.', 5, 'Chicken Curry'),
             ('Pour in coconut milk and add diced tomatoes if using.', 6, 'Chicken Curry'),
             ('Bring to a gentle simmer, then reduce heat and cook for 20-25 minutes until chicken is tender.', 7,
              'Chicken Curry'),
             ('Taste and adjust seasoning with salt, pepper, and additional curry powder if needed.', 8,
              'Chicken Curry'),
             ('Garnish with fresh cilantro and serve over steamed rice.', 9, 'Chicken Curry'),
             ('Wash romaine lettuce thoroughly and pat completely dry with paper towels.', 1, 'Caesar Salad'),
             ('Tear lettuce into bite-sized pieces and place in a large salad bowl.', 2, 'Caesar Salad'),
             ('If making homemade croutons, cube bread and toast with olive oil until golden.', 3, 'Caesar Salad'),
             ('Prepare Caesar dressing by whisking together mayo, lemon juice, garlic, and anchovies.', 4,
              'Caesar Salad'),
             ('Add croutons to the lettuce and toss gently to combine.', 5, 'Caesar Salad'),
             ('Drizzle with Caesar dressing and toss until all leaves are well coated.', 6, 'Caesar Salad'),
             ('Top with freshly grated Parmesan cheese and freshly cracked black pepper.', 7, 'Caesar Salad'),
             ('Preheat oven to 180°C (350°F) and line baking sheets with parchment paper.', 1,
              'Chocolate Chip Cookies'),
             ('In a large bowl, cream together softened butter and both brown and white sugars until fluffy.', 2,
              'Chocolate Chip Cookies'),
             ('Beat in eggs one at a time, then add vanilla extract.', 3, 'Chocolate Chip Cookies'),
             ('In a separate bowl, whisk together flour, baking soda, and salt.', 4, 'Chocolate Chip Cookies'),
             ('Gradually mix the dry ingredients into the wet ingredients until just combined.', 5,
              'Chocolate Chip Cookies'),
             ('Fold in chocolate chips, being careful not to overmix the dough.', 6, 'Chocolate Chip Cookies'),
             ('Scoop dough into rounded tablespoons and place 2 inches apart on baking sheets.', 7,
              'Chocolate Chip Cookies'),
             ('Bake for 10-12 minutes until edges are golden but centers still look slightly underbaked.', 8,
              'Chocolate Chip Cookies'),
             ('Cool on baking sheet for 5 minutes before transferring to a wire rack.', 9, 'Chocolate Chip Cookies'),
             ('Heat vegetable or chicken stock in a separate pot and keep warm throughout cooking.', 1,
              'Mushroom Risotto'),
             ('Clean and slice mushrooms, separating different varieties if using a mix.', 2, 'Mushroom Risotto'),
             ('Heat butter and olive oil in a large, heavy-bottomed pan over medium heat.', 3, 'Mushroom Risotto'),
             ('Sauté mushrooms until golden brown and their moisture has evaporated, about 8-10 minutes.', 4,
              'Mushroom Risotto'),
             ('Remove mushrooms and set aside, leaving any remaining oil in the pan.', 5, 'Mushroom Risotto'),
             ('Add diced onions to the same pan and cook until translucent, about 5 minutes.', 6, 'Mushroom Risotto'),
             ('Add Arborio rice and stir for 2-3 minutes until grains are lightly toasted and coated.', 7,
              'Mushroom Risotto'),
             ('Pour in white wine and stir until completely absorbed.', 8, 'Mushroom Risotto'),
             ('Add warm stock one ladle at a time, stirring constantly until each addition is absorbed.', 9,
              'Mushroom Risotto'),
             ('Continue this process for 18-20 minutes until rice is creamy and al dente.', 10, 'Mushroom Risotto'),
             ('Stir in the cooked mushrooms, butter, and Parmesan cheese.', 11, 'Mushroom Risotto'),
             ('Season with salt, pepper, and fresh herbs before serving immediately.', 12, 'Mushroom Risotto'),
             ('Pat fish fillets dry and season with cumin, chili powder, salt, and pepper.', 1, 'Fish Tacos'),
             ('Heat oil in a large skillet over medium-high heat.', 2, 'Fish Tacos'),
             ('Cook fish for 3-4 minutes per side until it flakes easily with a fork.', 3, 'Fish Tacos'),
             ('Remove fish from heat and break into bite-sized pieces.', 4, 'Fish Tacos'),
             ('Warm corn tortillas in a dry skillet or directly over gas flame until lightly charred.', 5,
              'Fish Tacos'),
             ('Prepare taco toppings: shred cabbage, dice tomatoes, and slice avocado.', 6, 'Fish Tacos'),
             ('Make quick salsa by mixing diced tomatoes, onions, cilantro, and lime juice.', 7, 'Fish Tacos'),
             ('Assemble tacos by placing fish in tortillas and topping with cabbage and salsa.', 8, 'Fish Tacos'),
             ('Serve with lime wedges and hot sauce on the side.', 9, 'Fish Tacos'),
             ('Wash and dice tomatoes into large chunks, removing excess seeds if desired.', 1, 'Greek Salad'),
             ('Peel cucumber and slice into thick rounds or half-moons.', 2, 'Greek Salad'),
             ('Thinly slice red onion and soak in cold water for 10 minutes to reduce sharpness.', 3, 'Greek Salad'),
             ('Cut feta cheese into cubes or break into large crumbles.', 4, 'Greek Salad'),
             ('Combine tomatoes, cucumber, drained onions, and olives in a large bowl.', 5, 'Greek Salad'),
             ('Whisk together olive oil, red wine vinegar, oregano, salt, and pepper for dressing.', 6, 'Greek Salad'),
             ('Pour dressing over vegetables and toss gently to combine.', 7, 'Greek Salad'),
             ('Top with feta cheese and additional oregano before serving.', 8, 'Greek Salad'),
             ('Slice beef against the grain into thin strips for tenderness.', 1, 'Beef Stir Fry'),
             ('Marinate beef in soy sauce, garlic, and ginger for at least 15 minutes.', 2, 'Beef Stir Fry'),
             ('Cut bell peppers into strips and prepare any other vegetables.', 3, 'Beef Stir Fry'),
             ('Heat oil in a wok or large skillet over high heat until smoking.', 4, 'Beef Stir Fry'),
             ('Add marinated beef and stir-fry for 2-3 minutes until just cooked through.', 5, 'Beef Stir Fry'),
             ('Remove beef and set aside to prevent overcooking.', 6, 'Beef Stir Fry'),
             ('Add vegetables to the same pan and stir-fry until crisp-tender, about 3-4 minutes.', 7, 'Beef Stir Fry'),
             ('Return beef to pan and toss everything together for 1 minute.', 8, 'Beef Stir Fry'),
             ('Serve immediately over steamed rice or noodles.', 9, 'Beef Stir Fry'),
             ('Preheat oven to 175°C (350°F) and grease a 9x5 inch loaf pan.', 1, 'Banana Bread'),
             ('In a large bowl, mash very ripe bananas until mostly smooth with some small lumps.', 2, 'Banana Bread'),
             ('Mix melted butter into the mashed bananas until well combined.', 3, 'Banana Bread'),
             ('Add sugar, beaten egg, and vanilla extract to the banana mixture.', 4, 'Banana Bread'),
             ('In a separate bowl, whisk together flour, baking soda, and salt.', 5, 'Banana Bread'),
             ('Gradually fold the dry ingredients into the wet ingredients until just combined.', 6, 'Banana Bread'),
             ('Pour batter into the prepared loaf pan and smooth the top.', 7, 'Banana Bread'),
             ('Bake for 55-65 minutes until a toothpick inserted in center comes out with just a few moist crumbs.', 8,
              'Banana Bread'),
             ('Cool in pan for 10 minutes, then turn out onto a wire rack to cool completely.', 9, 'Banana Bread'),
             ('Heat olive oil in a large pot over medium heat.', 1, 'Vegetable Soup'),
             ('Add diced onions and cook until softened and translucent, about 5-6 minutes.', 2, 'Vegetable Soup'),
             ('Add minced garlic and cook for another minute until fragrant.', 3, 'Vegetable Soup'),
             ('Add diced carrots and celery, cook for 5 minutes until slightly softened.', 4, 'Vegetable Soup'),
             ('Pour in vegetable broth and bring to a boil.', 5, 'Vegetable Soup'),
             ('Add any harder vegetables like potatoes or squash and simmer for 10 minutes.', 6, 'Vegetable Soup'),
             ('Add softer vegetables like zucchini, green beans, or peas.', 7, 'Vegetable Soup'),
             ('Continue simmering for 10-15 minutes until all vegetables are tender.', 8, 'Vegetable Soup'),
             ('Season with salt, pepper, and fresh herbs like thyme or parsley.', 9, 'Vegetable Soup'),
             ('Taste and adjust seasoning before serving hot with crusty bread.', 10,
              'Vegetable Soup')) AS steps(description, position, recipe_title)
         JOIN recipe r ON r.title = steps.recipe_title
ON CONFLICT DO NOTHING;
