services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: recipe_book
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/db:/docker-entrypoint-initdb.d

  quarkus:
    build:
      context: .
      dockerfile: ./app/src/main/docker/Dockerfile.jvm
    environment:
      POSTGRES_PASSWORD: localdevpassword
      BACKEND_HOST_URL: localhost:8081
    ports:
      - "8081:8081"
volumes:
  pg_data: