services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: quarkus_password
      POSTGRES_DB: recipe_book
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/db/schema:/docker-entrypoint-initdb.d/schema

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: b.blaauwendraad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    depends_on:
        - postgres
    volumes:
      - ./app/db/pgadmin-servers.json:/pgadmin4/pgadmin-servers.json:ro

  quarkus_app:
    build:
      context: .
      dockerfile: app/src/main/docker/Dockerfile.jvm
    container_name: quarkus_app
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/recipe_book
      QUARKUS_DATASOURCE_USERNAME: quarkus_user
      QUARKUS_DATASOURCE_PASSWORD: quarkus_password
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "8080:8080"
volumes:
  pg_data: