# This file is used for local development only
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: recipe_book
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./app/db:/docker-entrypoint-initdb.d

  quarkus:
    build:
      context: ./app
      dockerfile: ./src/main/docker/Dockerfile.jvm
    environment:
      POSTGRES_PASSWORD: localdevpassword
      PUB_KEY_LOCATION: classpath:local-dev-keys/publicKey.pem
      PRIV_KEY_LOCATION: classpath:local-dev-keys/privateKey.pem
    ports:
      - "8081:8081"
volumes:
  pg_data: