services:
  postgres:
    image: postgres:latest
    container_name: recipe_book_pg_db
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: quarkus_password
      POSTGRES_DB: recipe_book
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: b.blaauwendraad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
        - postgres

  quarkus_app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: recipe_book_app
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/recipe_book
      QUARKUS_DATASOURCE_USERNAME: quarkus_user
      QUARKUS_DATASOURCE_PASSWORD: quarkus_password
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "8080:8080"
volumes:
  pg_data: